# Generated by Django 2.1.1 on 2018-10-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multichoice',
            name='opinion',
        ),
        migrations.RemoveField(
            model_name='truefalse',
            name='opinion',
        ),
    ]
