# Generated by Django 2.1.1 on 2018-10-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20181011_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truefalse',
            options={'ordering': ['index'], 'verbose_name': 'True or false item'},
        ),
        migrations.AddField(
            model_name='multichoice',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='truefalse',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
