# Generated by Django 2.1.1 on 2018-10-15 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0004_auto_20181014_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.SmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity')),
                ('response', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Response')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='completed',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='completed',
            name='user',
        ),
        migrations.AddField(
            model_name='multichoice',
            name='item_type',
            field=models.CharField(choices=[('OP', 'Open'), ('SA', 'Semi-Anonymous'), ('AN', 'Anonymous')], default='OP', max_length=2),
        ),
        migrations.AddField(
            model_name='truefalse',
            name='item_type',
            field=models.CharField(choices=[('OP', 'Open'), ('SA', 'Semi-Anonymous'), ('AN', 'Anonymous')], default='OP', max_length=2),
        ),
        migrations.DeleteModel(
            name='Completed',
        ),
    ]
