# Generated by Django 2.1.1 on 2018-10-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0007_auto_20181015_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyChoice',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity.Choice')),
                ('votes', models.PositiveIntegerField(default=0)),
            ],
            bases=('activity.choice',),
        ),
        migrations.CreateModel(
            name='SurveyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.SmallIntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=25, null=True)),
                ('opinion', models.BooleanField(default=False)),
                ('privacy_type', models.CharField(choices=[('OP', 'Open'), ('SA', 'Semi-Anonymous'), ('AN', 'Anonymous')], default='OP', max_length=2)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity')),
            ],
            options={
                'ordering': ['index'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyMultiChoice',
            fields=[
                ('multichoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity.MultiChoice')),
            ],
            options={
                'ordering': ['index'],
                'abstract': False,
            },
            bases=('activity.multichoice',),
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('response_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity.Response')),
            ],
            bases=('activity.response',),
        ),
        migrations.CreateModel(
            name='SurveyTrueFalse',
            fields=[
                ('truefalse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity.TrueFalse')),
                ('true_count', models.PositiveIntegerField(default=0)),
                ('false_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['index'],
                'abstract': False,
            },
            bases=('activity.truefalse',),
        ),
    ]
