# Generated by Django 2.1.1 on 2018-10-20 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyChoice',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity.Choice')),
                ('votes', models.PositiveIntegerField(default=0)),
            ],
            bases=('activity.choice',),
        ),
        migrations.CreateModel(
            name='SurveyItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity.Item')),
            ],
            bases=('activity.item',),
        ),
        migrations.CreateModel(
            name='SurveyMultiChoice',
            fields=[
                ('multichoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity.MultiChoice')),
            ],
            options={
                'verbose_name': 'survey multiple choice item',
            },
            bases=('activity.multichoice',),
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('response_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity.Response')),
            ],
            bases=('activity.response',),
        ),
        migrations.CreateModel(
            name='SurveyTrueFalse',
            fields=[
                ('truefalse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity.TrueFalse')),
                ('true_count', models.PositiveIntegerField(default=0)),
                ('false_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'survey true/false item',
            },
            bases=('activity.truefalse',),
        ),
    ]
